export { authApi } from './modules/auth'
export { userApi } from './modules/user'
export { competitionApi } from './modules/competition'
export { registrationApi } from './modules/registration'
export { resultApi } from './modules/result'
export { exportApi } from './modules/export'
export { recruitApi } from './modules/recruit'
export { communityApi } from './modules/community'
export { notificationApi } from './modules/notification'
export { noticeApi, statsApi, fileApi } from './modules/system'
